language: elixir
matrix:
  include:
    - elixir: 1.5.3
      otp_release: 20.3
    - elixir: 1.8.2
      otp_release: 21.3
    - elixir: 1.9.1
      otp_release: 22.0
notifications:
  recipients:
    - jose.valim@dashbit.co
